package com.streamflixreborn.streamflix.utils

object Strings {
    fun get(key: String, lang: String = AppSettings.data.appLanguage): String {
        return when (lang.lowercase().substringBefore("-")) {
            "de" -> when (key) {
                "Home" -> "Startseite"
                "Movies" -> "Filme"
                "TV Shows" -> "Serien"
                "Favorites" -> "Favoriten"
                "Settings" -> "Einstellungen"
                "Continue Watching" -> "Weiterschauen"
                "Search" -> "Suchen"
                "Trending" -> "Angesagt"
                "Popular Movies" -> "Beliebte Filme"
                "Popular TV Shows" -> "Beliebte Serien"
                "Play" -> "Abspielen"
                "Details" -> "Details"
                "Quality" -> "Qualität"
                "Audio" -> "Audio"
                "Subs" -> "Untertitel"
                "Speed" -> "Geschwindigkeit"
                "Aspect" -> "Bildformat"
                "Autoplay Next Episode" -> "Nächste Folge automatisch abspielen"
                "Clear History" -> "Verlauf löschen"
                "App Language" -> "App-Sprache"
                "Select Provider" -> "Provider auswählen"
                "All" -> "Alle"
                "Playback Settings" -> "Wiedergabe-Einstellungen"
                "Current Provider" -> "Aktueller Provider"
                "Change Provider" -> "Provider wechseln"
                "Clear Watch History" -> "Wiedergabeverlauf leeren"
                "Episode" -> "Folge"
                "Season" -> "Staffel"
                else -> key
            }
            "ru" -> when (key) {
                "Home" -> "Главная"
                "Movies" -> "Фильмы"
                "TV Shows" -> "Сериалы"
                "Favorites" -> "Избранное"
                "Settings" -> "Настройки"
                "Continue Watching" -> "Продолжить просмотр"
                "Search" -> "Поиск"
                "Trending" -> "В тренде"
                "Popular Movies" -> "Популярные фильмы"
                "Popular TV Shows" -> "Популярные сериалы"
                "Play" -> "Смотреть"
                "Details" -> "Подробнее"
                "Quality" -> "Качество"
                "Audio" -> "Аудио"
                "Subs" -> "Субтитры"
                "Speed" -> "Скорость"
                "Aspect" -> "Формат"
                "Autoplay Next Episode" -> "Автовоспроизведение следующей серии"
                "Clear History" -> "Очистить историю"
                "App Language" -> "Язык приложения"
                "Select Provider" -> "Выбрать источник"
                "All" -> "Все"
                "Playback Settings" -> "Настройки воспроизведения"
                "Current Provider" -> "Текущий источник"
                "Change Provider" -> "Сменить источник"
                "Clear Watch History" -> "Очистить историю просмотров"
                "Episode" -> "Эпизод"
                "Season" -> "Сезон"
                else -> key
            }
            "es" -> when (key) {
                "Home" -> "Inicio"
                "Movies" -> "Películas"
                "TV Shows" -> "Series"
                "Favorites" -> "Favoritos"
                "Settings" -> "Ajustes"
                "Continue Watching" -> "Continuar viendo"
                "Search" -> "Buscar"
                "Trending" -> "Tendencias"
                "Popular Movies" -> "Películas populares"
                "Popular TV Shows" -> "Series populares"
                "Play" -> "Reproducir"
                "Details" -> "Detalles"
                "Quality" -> "Calidad"
                "Audio" -> "Audio"
                "Subs" -> "Subtítulos"
                "Speed" -> "Velocidad"
                "Aspect" -> "Formato"
                "Autoplay Next Episode" -> "Reproducir siguiente episodio"
                "Clear History" -> "Borrar historial"
                "App Language" -> "Idioma de la aplicación"
                "Select Provider" -> "Seleccionar proveedor"
                "All" -> "Todo"
                "Playback Settings" -> "Ajustes de reproducción"
                "Current Provider" -> "Proveedor actual"
                "Change Provider" -> "Cambiar proveedor"
                "Clear Watch History" -> "Borrar historial de visualización"
                "Episode" -> "Episodio"
                "Season" -> "Temporada"
                else -> key
            }
            "fr" -> when (key) {
                "Home" -> "Accueil"
                "Movies" -> "Films"
                "TV Shows" -> "Séries"
                "Favorites" -> "Favoris"
                "Settings" -> "Paramètres"
                "Continue Watching" -> "Reprendre la lecture"
                "Search" -> "Rechercher"
                "Trending" -> "Tendances"
                "Popular Movies" -> "Films populaires"
                "Popular TV Shows" -> "Séries populaires"
                "Play" -> "Lire"
                "Details" -> "Détails"
                "Quality" -> "Qualité"
                "Audio" -> "Audio"
                "Subs" -> "Sous-titres"
                "Speed" -> "Vitesse"
                "Aspect" -> "Format"
                "Autoplay Next Episode" -> "Épisode suivant automatique"
                "Clear History" -> "Effacer l'historique"
                "App Language" -> "Langue de l'application"
                "Select Provider" -> "Sélectionner la source"
                "All" -> "Tout"
                "Playback Settings" -> "Paramètres de lecture"
                "Current Provider" -> "Source actuelle"
                "Change Provider" -> "Changer de source"
                "Clear Watch History" -> "Effacer l'historique de lecture"
                "Episode" -> "Épisode"
                "Season" -> "Saison"
                else -> key
            }
            "it" -> when (key) {
                "Home" -> "Home"
                "Movies" -> "Film"
                "TV Shows" -> "Serie TV"
                "Favorites" -> "Preferiti"
                "Settings" -> "Impostazioni"
                "Continue Watching" -> "Continua a guardare"
                "Search" -> "Cerca"
                "Trending" -> "Di tendenza"
                "Popular Movies" -> "Film popolari"
                "Popular TV Shows" -> "Serie TV popolari"
                "Play" -> "Riproduci"
                "Details" -> "Dettagli"
                "Quality" -> "Qualità"
                "Audio" -> "Audio"
                "Subs" -> "Sottotitoli"
                "Speed" -> "Velocità"
                "Aspect" -> "Formato"
                "Autoplay Next Episode" -> "Riproduci episodio successivo"
                "Clear History" -> "Cancella cronologia"
                "App Language" -> "Lingua dell'applicazione"
                "Select Provider" -> "Seleziona sorgente"
                "All" -> "Tutti"
                "Playback Settings" -> "Impostazioni di riproduzione"
                "Current Provider" -> "Sorgente attuale"
                "Change Provider" -> "Cambia sorgente"
                "Clear Watch History" -> "Cancella cronologia di visualizzazione"
                "Episode" -> "Episodio"
                "Season" -> "Stagione"
                else -> key
            }
            "pl" -> when (key) {
                "Home" -> "Główna"
                "Movies" -> "Filmy"
                "TV Shows" -> "Seriale"
                "Favorites" -> "Ulubione"
                "Settings" -> "Ustawienia"
                "Continue Watching" -> "Kontynuuj oglądanie"
                "Search" -> "Szukaj"
                "Trending" -> "Na czasie"
                "Popular Movies" -> "Popularne filmy"
                "Popular TV Shows" -> "Popularne seriale"
                "Play" -> "Odtwórz"
                "Details" -> "Szczegóły"
                "Quality" -> "Jakość"
                "Audio" -> "Dźwięk"
                "Subs" -> "Napisy"
                "Speed" -> "Prędkość"
                "Aspect" -> "Format"
                "Autoplay Next Episode" -> "Autoodtwarzanie kolejnego odcinka"
                "Clear History" -> "Wyczyść historię"
                "App Language" -> "Język aplikacji"
                "Select Provider" -> "Wybierz źródło"
                "All" -> "Wszystko"
                "Playback Settings" -> "Ustawienia odtwarzania"
                "Current Provider" -> "Aktualne źródło"
                "Change Provider" -> "Zmień źródło"
                "Clear Watch History" -> "Wyczyść historię oglądania"
                "Episode" -> "Odcinek"
                "Season" -> "Sezon"
                else -> key
            }
            "pt" -> when (key) {
                "Home" -> "Início"
                "Movies" -> "Filmes"
                "TV Shows" -> "Séries"
                "Favorites" -> "Favoritos"
                "Settings" -> "Definições"
                "Continue Watching" -> "Continuar a ver"
                "Search" -> "Pesquisar"
                "Trending" -> "Tendências"
                "Popular Movies" -> "Filmes Populares"
                "Popular TV Shows" -> "Séries Populares"
                "Play" -> "Reproduzir"
                "Details" -> "Detalhes"
                "Quality" -> "Qualidade"
                "Audio" -> "Áudio"
                "Subs" -> "Legendas"
                "Speed" -> "Velocidade"
                "Aspect" -> "Formato"
                "Autoplay Next Episode" -> "Reproduzir próximo episódio automaticamente"
                "Clear History" -> "Limpar histórico"
                "App Language" -> "Idioma da aplicação"
                "Select Provider" -> "Selecionar fornecedor"
                "All" -> "Tudo"
                "Playback Settings" -> "Definições de reprodução"
                "Current Provider" -> "Fornecedor atual"
                "Change Provider" -> "Mudar fornecedor"
                "Clear Watch History" -> "Limpar histórico de reprodução"
                "Episode" -> "Episódio"
                "Season" -> "Temporada"
                else -> key
            }
            else -> key
        }
    }
}
